question_data = [
    {"text": "In 'Team Fortress 2', the 'Bill's Hat' is a reference to the game 'Dota 2'.",
        "answer": "False"},
    {"text": "Kissing someone for one minute burns about 2 calories.",
        "answer": "True"},
    {"text": "The Olympics tennis court is a giant green screen.",
     "answer": "True"},
    {"text": "The sum of all the numbers on a roulette wheel is 666.",
     "answer": "True"},
    {"text": "In 'Avatar: The Last Airbender' and 'The Legend of Korra', Lavabending is a specialized bending technique of Firebending.",
     "answer": "False"},
    {"text": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body's inertia.",
     "answer": "False"},
    {"text": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
     "answer": "True"},
    {"text": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
     "answer": "True"},
    {"text": "'Kamea,' the Gilbertese Islander word for dog, is derived from the English phrase 'Come here!'",
     "answer": "True"},
    {"text": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
     "answer": "False"},
    {"text": "The vapor produced by e-cigarettes is actually water.",
     "answer": "False"},
    {"text": "'Return to Castle Wolfenstein' was the only game of the Wolfenstein series where you don't play as William 'B.J.' Blazkowicz.",
     "answer": "False"},
    {"text": "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
     "answer": "True"},
    {"text": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
     "answer": "True"},
    {"text": "Formula E is an auto racing series that uses hybrid electric race cars.",
     "answer": "False"},
    {"text": "In Portal, the Companion Cube's ARE sentient.",
     "answer": "True"},
    {"text": "Rapper Snoop Dogg's real name is 'Cordozar Calvin Broadus, Jr.'.",
     "answer": "True"},
    {"text": "Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.",
     "answer": "True"},
    {"text": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "answer": "False"},
    {"text": "In 'Star Trek', Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
     "answer": "True"}]